services:
  mongo:
    image: mongo:8.0
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always

  mysql9:
    image: mysql:9.0-oracle
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: [
      "mysqld",
      "--innodb_file_per_table=0",
      "--innodb_doublewrite=0",
      "--skip-name-resolve"
    ]
    volumes:
      - mysql9:/var/lib/mysql

  mariadb:
    image: mariadb:12
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  postgis:
    image: imresamu/postgis:16-3.4
    ports:
      - "5433:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-CTP2.0-ubuntu-22.04
    restart: always
    platform: linux/amd64
    ports:
      - '1433:1433'
    environment:
      MSSQL_SA_PASSWORD: Root.Root
      MSSQL_TELEMETRY_ENABLED: 0
      ACCEPT_EULA: 1
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]

volumes:
  mysql9:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mariadb:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgre:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgis:
    driver_opts:
      type: tmpfs
      device: tmpfs
